INSERT INTO AUTHORITY(ID, NAME, IS_DELETED) VALUES (1, 'ADMIN', FALSE);
INSERT INTO AUTHORITY(ID, NAME, IS_DELETED) VALUES (2, 'PROFESSOR', FALSE);
INSERT INTO AUTHORITY(ID, NAME, IS_DELETED) VALUES (3, 'STUDENT', FALSE);
