INSERT INTO USER_(ID, USER_NAME, PASSWORD, AUTHORITY_ID, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, IS_DELETED)
  VALUES (1, 'admin', /*admin1234*/'$2a$08$qvrzQZ7jJ7oy2p/msL4M0.l83Cd0jNsX6AJUitbgRXGzge4j035ha',1 , FALSE, FALSE, FALSE, TRUE, FALSE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, AUTHORITY_ID, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, IS_DELETED)
   VALUES (2, 'professor', /*professor1234*/'$2y$08$g2ryBm8IQM9ujoPIdA47eu.rLQ2Ecu2jDKfFPwYTvGkwJF1ebjnbG', 2, FALSE, FALSE, FALSE, TRUE, FALSE);
