INSERT INTO ROLE(ID, NAME, IS_DELETED) VALUES (1, 'ROLE_ADMIN', FALSE);
INSERT INTO ROLE(ID, NAME, IS_DELETED) VALUES (2, 'ROLE_PROFESSOR', FALSE);
INSERT INTO ROLE(ID, NAME, IS_DELETED) VALUES (3, 'ROLE_STUDENT', FALSE);
